### ISSUE TITLE
Create a custom 404 page

### ISSUE THREAD

**Issue by marcusramberg** [oslo-pm/oslo-pm.github.io#14]
Would be nice if our 404 has the same style as the rest of the site.

**Comment by jhthorsen** [comment]
Maybe we can add a YouTube video or a list of resources the person could check out? See also #13 for ideas about the list of resources.

Here is my suggestion:

```
$ cat > 404.md
---
layout: default
title: Page not found
permalink: /404.html
---

# Could not find the requested page (404)

Sorry, but the requested page could not be found. Maybe you want to check out
these resources instead?

* [About Oslo.pm](/about)
* [Oslo.pm's blog](/blog)
* [Perl.org](https://www.perl.org/)
* [Perl weekly](http://perlweekly.com/)
* [Search for Perl modules](https://metacpan.org/)

^C
```

https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/
