### ISSUE TITLE
Update board/index.md with current information

### ISSUE THREAD

**Issue by jhthorsen** [oslo-pm/oslo-pm.github.io#3]
Would be nice if we created `board/2016-12-01.md` (or something) and symlinked that into `board/index.md`.

Would it be nice to add pictures?

**Comment by krunen** [comment]
La inn 2016-11-02.md. Jeg ser du har ekstra stuff i index.md, så kanskje du kan fikse resten?

**Comment by jhthorsen** [comment]
Suverent 👍
