### ISSUE TITLE
Make oslo.pm.org, oslo.pm and friends point to home.oslo.pm

### ISSUE THREAD

**Issue by jhthorsen** [oslo-pm/oslo-pm.github.io#6]
Would be nice if oslo.pm and other related domains could point to this github project.

I suggest making the DNS changes and update https://github.com/oslo-pm/oslo-pm.github.io/blob/master/CNAME to `oslo.pm` or `www.oslo.pm`.

I'm not quite sure how you're going to solve the redirect rules, but I can always set up nginx rules on a digitalocean server to do this. I also know that it would be very simple to manage if we had https://www.cloudflare.com/ infront (zero cost).

**Comment by sjn** [comment]
I've updated the domain settings on GANDI.NET so oslo.pm and www.oslo.pm forward to home.oslo.pm.

We have also the option to change our "main" address to just "oslo.pm", btw.

the oslo.pm.org domain is managed by the Perl NOC team. I'll send them a mail to update their records.

**Comment by jhthorsen** [comment]
Cool! I think we should change the main address as well.

**Comment by sjn** [comment]
Mail sent to support at pm.org about updating DNS. I've also started the process with switching DNS servers to the new ones GANDI offers, so we later can make oslo.pm the main domain.

**Comment by sjn** [comment]
T'is all done now.
