### ISSUE TITLE
Is there any content from the old page that is not present?

### ISSUE THREAD

**Issue by jhthorsen** [oslo-pm/oslo-pm.github.io#7]
Is there anything you want to move from the old site to gh-pages @sjn?

**Comment by sjn** [comment]
I think having historic/old announcements would be nice.

**Comment by jhthorsen** [comment]
What does that mean?

We have a lot of old entries on the site: http://home.oslo.pm/blog/all/page13/

I also imported some events that i found on http://oslo.pm.org/: https://github.com/oslo-pm/oslo-pm.github.io/commit/05f2189ccbb843edf00d206ffc6c8359368d1f5f

```
<!--#include virtual="arrangementer/2014-03-24-damian-conway-kurs.html" -->
<!--#include virtual="arrangementer/2014-05-23-mojolicious-kurs.html" -->
<!--#include virtual="arrangementer/2014-05-24-mojoconf.html" -->
<!--#include virtual="arrangementer/2014-05-25-mojolicious-hackathon.html" -->
```

**Comment by sjn** [comment]
Ah, didn't see those. Awesome to see those! 😄
